# Generated by Django 5.2.5 on 2025-10-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('página_deportiva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitro',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='capacidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='dorsal',
            field=models.IntegerField(),
        ),
    ]
