# Generated by Django 5.2.5 on 2025-12-15 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('página_deportiva', '0002_alter_arbitro_edad_alter_estadio_capacidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='página_deportiva.equipo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='página_deportiva.partido')),
            ],
            options={
                'unique_together': {('equipo', 'partido')},
            },
        ),
        migrations.CreateModel(
            name='JugadorEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='página_deportiva.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='página_deportiva.jugador')),
            ],
            options={
                'unique_together': {('jugador', 'equipo')},
            },
        ),
        migrations.CreateModel(
            name='JugadorPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Arbitro',
        ),
        migrations.DeleteModel(
            name='Estadio',
        ),
        migrations.AddField(
            model_name='partido',
            name='equipos',
            field=models.ManyToManyField(related_name='partidos', through='página_deportiva.EquipoPartido', to='página_deportiva.equipo'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='equipos',
            field=models.ManyToManyField(related_name='jugadores', through='página_deportiva.JugadorEquipo', to='página_deportiva.equipo'),
        ),
        migrations.AddField(
            model_name='jugadorpartido',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='página_deportiva.jugador'),
        ),
        migrations.AddField(
            model_name='jugadorpartido',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='página_deportiva.partido'),
        ),
        migrations.AddField(
            model_name='partido',
            name='jugadores',
            field=models.ManyToManyField(related_name='partidos', through='página_deportiva.JugadorPartido', to='página_deportiva.jugador'),
        ),
        migrations.AlterUniqueTogether(
            name='jugadorpartido',
            unique_together={('jugador', 'partido')},
        ),
    ]
